Fix `initial_data.json` syntax (#26)
Trailing commas are not allowed in JSON, and consequently
Python's `json` module refuses to parse it.

  $ python -c '__import__("json").load(open("initial_data.json"))'
  [...]
  json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 86 column 5 (char 1923)

Fixes: 254f5106d28587 ("Adjust initial_data.json to model changes")